"""
Plot data model for handling generated visualizations.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class PlotData:
    """
    Represents a plot generated by Gemini's code execution.
    
    Attributes:
        image_data: Binary image data (PNG/JPEG)
        mime_type: MIME type of the image
        description: Optional description of the plot
    """
    image_data: bytes
    mime_type: str
    description: Optional[str] = None
    
    def is_valid(self) -> bool:
        """
        Check if the plot data is valid.
        
        Returns:
            True if image data exists and mime type is supported
        """
        from .constants import AppConfig
        return (
            self.image_data is not None 
            and len(self.image_data) > 0
            and self.mime_type in AppConfig.PLOT_MIME_TYPES
        )
